package pe.com.cpp.queue.service;
import java.time.*; import java.util.*; import org.springframework.dao.DataIntegrityViolationException; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.*; import pe.com.cpp.queue.api.*; import pe.com.cpp.queue.domain.*; import pe.com.cpp.queue.exception.*; import pe.com.cpp.queue.repository.*;
@Service public class QueueService {
 private final QueueTicketRepository tickets; private final DailyTicketSequenceRepository sequences; private final Clock clock;
 public QueueService(QueueTicketRepository tickets,DailyTicketSequenceRepository sequences,Clock clock){this.tickets=tickets;this.sequences=sequences;this.clock=clock;}
 @Transactional public TicketResponse issue(){LocalDate date=today();DailyTicketSequence sequence=lockedSequence(date);int value=sequence.takeNext();QueueTicket ticket=new QueueTicket("A-"+String.format("%03d",value),date,now());try{return toResponse(tickets.saveAndFlush(ticket));}catch(DataIntegrityViolationException e){throw new QueueConflictException("No fue posible asignar un número de ticket único",e);}}
 @Transactional public TicketResponse issueForAppointment(Integer appointmentId,Integer patientId){var existing=tickets.findByAppointmentId(appointmentId);if(existing.isPresent()){if(existing.get().getPatientId()!=null&&!existing.get().getPatientId().equals(patientId))throw new QueueConflictException("La cita ya tiene un ticket de otro paciente");return toResponse(existing.get());}LocalDate date=today();DailyTicketSequence sequence=lockedSequence(date);int value=sequence.takeNext();QueueTicket ticket=new QueueTicket("A-"+String.format("%03d",value),date,now(),appointmentId,patientId);try{return toResponse(tickets.saveAndFlush(ticket));}catch(DataIntegrityViolationException e){QueueTicket saved=tickets.findByAppointmentId(appointmentId).orElseThrow(()->new QueueConflictException("La cita ya tiene un ticket emitido",e));if(saved.getPatientId()!=null&&!saved.getPatientId().equals(patientId))throw new QueueConflictException("La cita ya tiene un ticket de otro paciente",e);return toResponse(saved);}}
 @Transactional(readOnly=true) public TicketResponse byAppointment(Integer appointmentId){return tickets.findByAppointmentId(appointmentId).map(this::toResponse).orElseThrow(()->new ResourceNotFoundException("La cita no tiene ticket emitido"));}
 @Transactional(readOnly=true) public List<TicketResponse> todayTickets(){return tickets.findByOperationalDateOrderByCreatedAtAsc(today()).stream().map(this::toResponse).toList();}
 @Transactional(readOnly=true) public List<TicketResponse> byStatus(TicketStatus status){return tickets.findByOperationalDateAndStatusOrderByCreatedAtAsc(today(),status).stream().map(this::toResponse).toList();}
 @Transactional(readOnly=true) public TicketResponse current(){return tickets.findFirstByOperationalDateAndStatusOrderByCreatedAtAsc(today(),TicketStatus.EN_ATENCION).map(this::toResponse).orElse(null);}
 @Transactional public TicketResponse call(Long id){LocalDate date=today();DailyTicketSequence sequence=lockedSequence(date);QueueTicket ticket=lockedTicket(id);if(!date.equals(ticket.getOperationalDate()))throw new QueueConflictException("Solo se pueden llamar tickets de la fecha operativa actual");try{sequence.activate(id);ticket.call(now());return toResponse(tickets.save(ticket));}catch(IllegalStateException e){throw new QueueConflictException(e.getMessage());}}
 @Transactional public TicketResponse finish(Long id){LocalDate date=today();DailyTicketSequence sequence=lockedSequence(date);QueueTicket ticket=lockedTicket(id);try{ticket.finish(now());sequence.clear(id);return toResponse(tickets.save(ticket));}catch(IllegalStateException e){throw new QueueConflictException(e.getMessage());}}
 @Transactional public TicketResponse attach(Long id,Integer appointmentId,Integer patientId){QueueTicket ticket=lockedTicket(id);tickets.findByAppointmentId(appointmentId).filter(existing->!existing.getId().equals(id)).ifPresent(existing->{throw new QueueConflictException("La cita ya tiene otro ticket vinculado");});try{ticket.attachToAppointment(appointmentId,patientId);return toResponse(tickets.saveAndFlush(ticket));}catch(IllegalStateException|IllegalArgumentException|DataIntegrityViolationException e){throw new QueueConflictException(e.getMessage(),e);}}
 @Transactional(readOnly=true) public DisplayResponse display(){TicketResponse current=current();List<TicketResponse> next=tickets.findByOperationalDateAndStatusOrderByCreatedAtAsc(today(),TicketStatus.ESPERA).stream().limit(3).map(this::toResponse).toList();return new DisplayResponse(current,next);}
 private DailyTicketSequence lockedSequence(LocalDate date){sequences.ensureExists(date);return sequences.findByDateForUpdate(date).orElseThrow(()->new QueueConflictException("No fue posible bloquear la secuencia diaria"));}
 private QueueTicket lockedTicket(Long id){return tickets.findByIdForUpdate(id).orElseThrow(()->new ResourceNotFoundException("Ticket no encontrado"));}
 private LocalDate today(){return LocalDate.now(clock);} private LocalDateTime now(){return LocalDateTime.now(clock);}
 private TicketResponse toResponse(QueueTicket t){return new TicketResponse(t.getId(),t.getNumber(),t.getOperationalDate(),t.getStatus(),t.getCreatedAt(),t.getCalledAt(),t.getFinishedAt(),t.getAppointmentId(),t.getPatientId());}
}
