services:

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: clinica_sqlserver
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Admin123!"
      MSSQL_PID: "Express"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    healthcheck:
      test: ["CMD", "/opt/mssql-tools18/bin/sqlcmd",
             "-S", "localhost", "-U", "sa", "-P", "Admin123!",
             "-No", "-Q", "SELECT 1"]
      interval: 15s
      timeout: 10s
      retries: 10
      start_period: 30s
    networks:
      - clinica_net

  db-init:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: clinica_db_init
    depends_on:
      sqlserver:
        condition: service_healthy
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Admin123!"
    volumes:
      - ./database/init-sqlserver.sql:/init.sql:ro
    entrypoint: /bin/bash
    command: >
      -c "/opt/mssql-tools18/bin/sqlcmd -S sqlserver -U sa -P 'Admin123!' -No -b -i /init.sql && echo 'Base de datos de identidad inicializada.'"
    networks:
      - clinica_net
    restart: "no"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: clinica_backend
    environment:
      DB_HOST: sqlserver
      DB_PORT: 1433
      DB_NAME: ClinicaPsicologia
      DB_USER: sa
      DB_PASSWORD: "Admin123!"
      APP_JWT_SECRET: "cLinIcApsIcOlOgIaPerU2025SecretKeyLong256BitsXXXXX"
      APP_JWT_EXPIRATION_MS: 86400000
      SPRING_PROFILES_ACTIVE: docker
      CORS_ALLOWED_ORIGINS: "http://20.12.223.112:4200,http://localhost:4200"
      CLINICAL_SERVICE_URL: http://clinical-service:8084
      QUEUE_SERVICE_URL: http://queue-service:8085
      PATIENT_SERVICE_URL: http://patient-service:8081
      SCHEDULING_SERVICE_URL: http://scheduling-service:8082
      BILLING_SERVICE_URL: http://billing-service:8083
      INTERNAL_API_KEY: cpp-internal-dev-key
    ports:
      - "8080:8080"
    depends_on:
      db-init:
        condition: service_completed_successfully
    networks:
      - clinica_net
      - cpp_network
    restart: on-failure

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: clinica_frontend
    ports:
      - "4200:80"
    depends_on:
      - backend
    networks:
      - clinica_net
      - cpp_network
    restart: on-failure

volumes:
  sqlserver_data:
    name: clinica_sqlserver_data

networks:
  clinica_net:
    name: clinica_network
    driver: bridge
  cpp_network:
    name: cpp-infrastructure_cpp-network
    external: true
