package pe.com.cpp.clinical.service;

import static org.junit.jupiter.api.Assertions.*; import static org.mockito.Mockito.*;
import java.time.*; import java.util.*; import org.junit.jupiter.api.*; import org.mockito.*; import org.springframework.test.util.ReflectionTestUtils;
import pe.com.cpp.clinical.api.*; import pe.com.cpp.clinical.client.*; import pe.com.cpp.clinical.domain.*; import pe.com.cpp.clinical.exception.*; import pe.com.cpp.clinical.repository.*;

class ClinicalServiceTest {
 @Mock TherapeuticProcessRepository processes; @Mock InitialInterviewRepository interviews; @Mock ClinicalSessionRepository sessions; @Mock PatientClient patients; @Mock SchedulingClient scheduling;
 ClinicalService service; TherapeuticProcess process;
 @BeforeEach void setUp(){MockitoAnnotations.openMocks(this);service=new ClinicalService(processes,interviews,sessions,patients,scheduling,Clock.fixed(Instant.parse("2026-07-12T15:00:00Z"),ZoneOffset.UTC));process=new TherapeuticProcess(1,"Ana Torres","76543210","HC-0001",1,"Jose Martinez",LocalDate.of(2026,7,12),null);}
 private ProcessCreateRequest startRequest(){return new ProcessCreateRequest(10,1,null,new InitialInterviewRequest("Ansiedad",null,null,null));}
 private AppointmentSnapshot appointment(){return new AppointmentSnapshot(10,"EN_CONSULTA",1,"Jose Martinez",1,"Ana Torres","76543210","HC-0001");}
 @Test void startsProcess(){when(patients.findById(1)).thenReturn(new PatientSnapshot(1,"HC-0001","76543210","Ana Torres",true));when(scheduling.findById(10)).thenReturn(appointment());when(processes.save(any())).thenAnswer(i->i.getArgument(0));when(interviews.save(any())).thenAnswer(i->i.getArgument(0));assertEquals(1,service.startProcess(1,startRequest()).currentPhase());}
 @Test void rejectsSecondActiveProcess(){when(processes.findByPatientIdAndActiveTrue(1)).thenReturn(Optional.of(process));assertThrows(DuplicateClinicalRecordException.class,()->service.startProcess(1,startRequest()));}
 @Test void updatesPhase(){when(processes.findById(1)).thenReturn(Optional.of(process));when(processes.save(process)).thenReturn(process);assertEquals(3,service.changePhase(1,new PhaseUpdateRequest(3,"avance" )).currentPhase());}
 @Test void rejectsPhaseChangeAfterDischarge(){process.changePhase(4,null);process.discharge(LocalDate.of(2026,7,13));when(processes.findById(1)).thenReturn(Optional.of(process));assertThrows(BusinessRuleException.class,()->service.changePhase(1,new PhaseUpdateRequest(3,null)));}
 @Test void rejectsInactiveProcessSession(){ReflectionTestUtils.setField(process,"active",false);when(processes.findById(1)).thenReturn(Optional.of(process));assertThrows(BusinessRuleException.class,()->service.registerSession(new SessionCreateRequest(1,10,1,"Mejora",null,"Dra.")));}
 @Test void rejectsDuplicateAppointment(){when(processes.findById(1)).thenReturn(Optional.of(process));when(sessions.existsByAppointmentId(10)).thenReturn(true);assertThrows(DuplicateClinicalRecordException.class,()->service.registerSession(new SessionCreateRequest(1,10,1,"Mejora",null,"Dra.")));}
 @Test void registersSessionAndMarksAppointment(){when(processes.findById(1)).thenReturn(Optional.of(process));when(scheduling.findById(10)).thenReturn(appointment());when(sessions.saveAndFlush(any())).thenAnswer(i->i.getArgument(0));service.registerSession(new SessionCreateRequest(1,10,null,"Mejora",null,"Dra."));verify(scheduling).markAttended(10);}
 @Test void listsSessionsInChronologicalOrder(){ReflectionTestUtils.setField(process,"id",1);ClinicalSession first=new ClinicalSession(process,10,2,"Primera evolución",null,"Dra.",LocalDateTime.of(2026,7,10,9,0));ClinicalSession second=new ClinicalSession(process,11,3,"Segunda evolución",null,"Dra.",LocalDateTime.of(2026,7,11,9,0));when(processes.findById(1)).thenReturn(Optional.of(process));when(sessions.findByProcessIdOrderByRegisteredAtAscIdAsc(1)).thenReturn(List.of(first,second));List<SessionResponse> result=service.sessionsForProcess(1);assertEquals(List.of("Primera evolución","Segunda evolución"),result.stream().map(SessionResponse::evolution).toList());verify(sessions).findByProcessIdOrderByRegisteredAtAscIdAsc(1);}
 @Test void rejectsAppointmentForAnotherPatient(){when(processes.findById(1)).thenReturn(Optional.of(process));when(scheduling.findById(10)).thenReturn(new AppointmentSnapshot(10,"EN_CONSULTA",1,"Jose",2,"Otro","1","HC"));assertThrows(BusinessRuleException.class,()->service.registerSession(new SessionCreateRequest(1,10,1,"Mejora",null,"Dra.")));}
 @Test void rejectsSessionForDifferentPhase(){when(processes.findById(1)).thenReturn(Optional.of(process));when(scheduling.findById(10)).thenReturn(appointment());assertThrows(BusinessRuleException.class,()->service.registerSession(new SessionCreateRequest(1,10,3,"Mejora",null,"Dra.")));verify(sessions,never()).saveAndFlush(any());}
 @Test void propagatesMissingPatient(){when(patients.findById(1)).thenThrow(new ResourceNotFoundException("Paciente no encontrado"));assertThrows(ResourceNotFoundException.class,()->service.startProcess(1,startRequest()));}
 @Test void propagatesExternalFailure(){when(patients.findById(1)).thenThrow(new ExternalServiceException("No disponible"));assertThrows(ExternalServiceException.class,()->service.startProcess(1,startRequest()));}
 @Test void startsExternalProcessWithoutCallingLegacyMicroservices(){when(processes.findByPatientIdAndActiveTrue(1)).thenReturn(Optional.empty());when(processes.findFirstByPatientIdOrderByStartDateDescIdDesc(1)).thenReturn(Optional.empty());when(processes.save(any())).thenAnswer(i->i.getArgument(0));when(interviews.save(any())).thenAnswer(i->i.getArgument(0));when(sessions.saveAndFlush(any())).thenAnswer(i->i.getArgument(0));ExternalProcessCreateRequest request=new ExternalProcessCreateRequest(10,1,"Jose Martinez","Ana Torres","76543210","HC-0001",null,new InitialInterviewRequest("Ansiedad",null,null,null));assertEquals(1,service.startExternalProcess(1,request).currentPhase());verifyNoInteractions(patients,scheduling);verify(sessions).saveAndFlush(any());}
 @Test void externalSessionRetryReturnsExistingRecord(){ReflectionTestUtils.setField(process,"id",1);ClinicalSession existing=new ClinicalSession(process,10,1,"Mejora",null,"Dra.",LocalDateTime.now());when(processes.findById(1)).thenReturn(Optional.of(process));when(sessions.findByAppointmentId(10)).thenReturn(Optional.of(existing));SessionResponse response=service.registerExternalSession(new ExternalSessionCreateRequest(1,10,1,"Mejora",null,"Dra."));assertEquals(10,response.appointmentId());verify(sessions,never()).saveAndFlush(any());}
 @Test void externalBridgeDoesNotReopenDischargedHistory(){process.changePhase(4,null);process.discharge(LocalDate.of(2026,7,13));when(processes.findByPatientIdAndActiveTrue(1)).thenReturn(Optional.empty());when(processes.findFirstByPatientIdOrderByStartDateDescIdDesc(1)).thenReturn(Optional.of(process));ExternalProcessCreateRequest request=new ExternalProcessCreateRequest(10,1,"Jose Martinez","Ana Torres","76543210","HC-0001",null,new InitialInterviewRequest("Ansiedad",null,null,null));assertThrows(BusinessRuleException.class,()->service.startExternalProcess(1,request));}
}
