package pe.com.cpp.clinical.service;
import static org.junit.jupiter.api.Assertions.*; import static org.mockito.Mockito.*;
import java.time.*; import java.util.*; import org.junit.jupiter.api.*; import org.mockito.*; import org.springframework.data.domain.Pageable; import org.springframework.test.util.ReflectionTestUtils; import pe.com.cpp.clinical.api.*; import pe.com.cpp.clinical.domain.*; import pe.com.cpp.clinical.exception.*; import pe.com.cpp.clinical.repository.*;
class DiagnosisServiceTest {
 @Mock Cie10DiagnosisRepository catalog; @Mock ClinicalHypothesisRepository hypotheses; @Mock HypothesisDiagnosisRepository assignments; @Mock TherapeuticProcessRepository processes; @Mock ClinicalSessionRepository sessions; DiagnosisService service; TherapeuticProcess process; Cie10Diagnosis anxiety;
 @BeforeEach void setUp(){MockitoAnnotations.openMocks(this);service=new DiagnosisService(catalog,hypotheses,assignments,processes,sessions,Clock.fixed(Instant.parse("2026-07-13T15:00:00Z"),ZoneOffset.UTC));process=new TherapeuticProcess(1,"Ana Torres","76543210","HC-0001",1,"Jose Martinez",LocalDate.of(2026,7,1),null);process.changePhase(2,null);ReflectionTestUtils.setField(process,"id",7);anxiety=mock(Cie10Diagnosis.class);when(anxiety.getCode()).thenReturn("F41.1");when(anxiety.getDescription()).thenReturn("Trastorno de ansiedad generalizada");when(anxiety.isActive()).thenReturn(true);}
 @Test void searchesCatalog(){when(catalog.search(eq("ansiedad"),any(Pageable.class))).thenReturn(List.of(anxiety));assertEquals("F41.1",service.search("ansiedad").get(0).code());}
 @Test void registersMultipleDiagnosesInPhaseTwo(){Cie10Diagnosis depression=mock(Cie10Diagnosis.class);when(depression.getCode()).thenReturn("F32.1");when(depression.getDescription()).thenReturn("Episodio depresivo moderado");when(depression.isActive()).thenReturn(true);when(processes.findById(7)).thenReturn(Optional.of(process));when(catalog.findByCodeInAndActiveTrue(anyList())).thenReturn(List.of(anxiety,depression));when(hypotheses.save(any())).thenAnswer(i->{ClinicalHypothesis h=i.getArgument(0);ReflectionTestUtils.setField(h,"id",3);return h;});HypothesisResponse response=service.register(7,new HypothesisCreateRequest(null,"Hipótesis","Plan",List.of("F41.1","F32.1"),"Dra. Ruiz"));assertEquals(2,response.diagnoses().size());verify(assignments).saveAll(argThat(items->((Collection<?>)items).size()==2));}
 @Test void rejectsRegistrationOutsidePhaseTwo(){process.changePhase(3,null);when(processes.findById(7)).thenReturn(Optional.of(process));assertThrows(BusinessRuleException.class,()->service.register(7,new HypothesisCreateRequest(null,"Hipótesis","Plan",List.of("F41.1"),"Dra.")));}
 @Test void rejectsUnknownCode(){when(processes.findById(7)).thenReturn(Optional.of(process));when(catalog.findByCodeInAndActiveTrue(anyList())).thenReturn(List.of());assertThrows(BusinessRuleException.class,()->service.register(7,new HypothesisCreateRequest(null,"Hipótesis","Plan",List.of("X00"),"Dra.")));}
}
