package pe.com.cpp.clinical.service;
import static org.junit.jupiter.api.Assertions.*; import static org.mockito.Mockito.*; import java.time.*; import java.util.*; import org.junit.jupiter.api.*; import org.mockito.*; import org.springframework.test.util.ReflectionTestUtils; import pe.com.cpp.clinical.api.*; import pe.com.cpp.clinical.client.*; import pe.com.cpp.clinical.domain.*; import pe.com.cpp.clinical.exception.*; import pe.com.cpp.clinical.repository.*;
class DischargeServiceTest {
 @Mock TherapeuticProcessRepository processes; @Mock ClinicalDischargeReportRepository reports; @Mock ClinicalSessionRepository sessions; @Mock QueueClient queue; DischargeService service; TherapeuticProcess process; DischargeRequest request;
 @BeforeEach void setUp(){MockitoAnnotations.openMocks(this);service=new DischargeService(processes,reports,sessions,queue,Clock.fixed(Instant.parse("2026-07-13T15:00:00Z"),ZoneOffset.UTC));process=new TherapeuticProcess(1,"Ana Torres","76543210","HC-0001",1,"Dra. Ruiz",LocalDate.of(2026,7,1),null,10);ReflectionTestUtils.setField(process,"id",7);when(queue.findByAppointment(10)).thenReturn(new QueueTicketSnapshot(4L,"A-004","FINALIZADO",LocalDateTime.of(2026,7,1,8,0),10,1));request=new DischargeRequest("Objetivos alcanzados","Doce sesiones de intervención","Regulación emocional","Seguimiento mensual","Dra. Ruiz");}
 @Test void dischargesPhaseFourAndGeneratesReport(){process.changePhase(4,null);when(processes.findById(7)).thenReturn(Optional.of(process));when(reports.save(any())).thenAnswer(i->i.getArgument(0));when(sessions.countByProcessId(7)).thenReturn(12L);DischargeReportResponse response=service.discharge(7,request);assertEquals("ALTA",response.status());assertEquals(12,response.sessionCount());assertEquals(LocalDate.of(2026,7,13),process.getEndDate());assertFalse(process.isActive());verify(processes).save(process);}
 @Test void rejectsDischargeOutsidePhaseFour(){when(processes.findById(7)).thenReturn(Optional.of(process));assertThrows(BusinessRuleException.class,()->service.discharge(7,request));verify(reports,never()).save(any());}
 @Test void rejectsSecondDischarge(){process.changePhase(4,null);when(processes.findById(7)).thenReturn(Optional.of(process));when(reports.existsByProcessId(7)).thenReturn(true);assertThrows(DuplicateClinicalRecordException.class,()->service.discharge(7,request));}
 @Test void returnsStoredReport(){process.changePhase(4,null);process.discharge(LocalDate.of(2026,7,13));ClinicalDischargeReport report=new ClinicalDischargeReport(process,"Motivo","Resumen","Logros","Recomendaciones","Dra.",LocalDateTime.of(2026,7,13,10,0));when(processes.findById(7)).thenReturn(Optional.of(process));when(reports.findByProcessId(7)).thenReturn(Optional.of(report));assertEquals("Resumen",service.report(7).treatmentSummary());}
 @Test void returnsLatestReportForPatient(){process.changePhase(4,null);process.discharge(LocalDate.of(2026,7,13));ClinicalDischargeReport report=new ClinicalDischargeReport(process,"Motivo","Resumen","Logros","Recomendaciones","Dra.",LocalDateTime.of(2026,7,13,10,0));when(processes.findFirstByPatientIdOrderByStartDateDescIdDesc(1)).thenReturn(Optional.of(process));when(processes.findById(7)).thenReturn(Optional.of(process));when(reports.findByProcessId(7)).thenReturn(Optional.of(report));assertEquals(7,service.latestReportForPatient(1).processId());}
}
