package pe.com.cpp.clinical.api;
import static org.mockito.ArgumentMatchers.*; import static org.mockito.Mockito.*; import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*; import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;
import java.time.LocalDate; import java.time.LocalDateTime; import java.util.List; import org.junit.jupiter.api.Test; import org.springframework.beans.factory.annotation.Autowired; import org.springframework.boot.test.autoconfigure.web.servlet.WebMvcTest; import org.springframework.http.MediaType; import org.springframework.test.context.bean.override.mockito.MockitoBean; import org.springframework.test.web.servlet.MockMvc; import pe.com.cpp.clinical.service.ClinicalService;
@WebMvcTest(ClinicalController.class) class ClinicalControllerTest {
 @Autowired MockMvc mvc; @MockitoBean ClinicalService service;
 private ProcessResponse process(){return new ProcessResponse(1,1,"Ana","76543210","HC-0001",1,"Jose",1,LocalDate.now(),null,null,true,"ACTIVO",null);}
 @Test void createsProcess() throws Exception{when(service.startProcess(eq(1),any())).thenReturn(process());mvc.perform(post("/api/clinical/patients/1/processes").contentType(MediaType.APPLICATION_JSON).content("{\"appointmentId\":10,\"psychologistId\":1,\"entrevista\":{\"motivoConsulta\":\"Ansiedad\"}}")).andExpect(status().isCreated()).andExpect(jsonPath("$.patientId").value(1));}
 @Test void rejectsBlankInterviewReason() throws Exception{mvc.perform(post("/api/clinical/patients/1/processes").contentType(MediaType.APPLICATION_JSON).content("{\"appointmentId\":10,\"psychologistId\":1,\"entrevista\":{\"motivoConsulta\":\"\"}}")).andExpect(status().isBadRequest());}
 @Test void rejectsPhaseOutsideRange() throws Exception{mvc.perform(patch("/api/clinical/processes/1/phase").contentType(MediaType.APPLICATION_JSON).content("{\"faseActual\":5}")).andExpect(status().isBadRequest());}
 @Test void listsSessions() throws Exception{when(service.sessionsForProcess(1)).thenReturn(List.of());mvc.perform(get("/api/clinical/processes/1/sessions")).andExpect(status().isOk()).andExpect(content().json("[]"));}
 @Test void createsAppendOnlySession() throws Exception{SessionResponse response=new SessionResponse(5,1,10,3,"El paciente presenta avances","Mantener ejercicios","Dra. Ruiz",LocalDateTime.of(2026,7,13,10,0));when(service.registerSession(any())).thenReturn(response);mvc.perform(post("/api/clinical/sessions").contentType(MediaType.APPLICATION_JSON).content("{\"processId\":1,\"appointmentId\":10,\"sessionPhase\":3,\"evolution\":\"El paciente presenta avances\",\"patientIndications\":\"Mantener ejercicios\",\"registeredBy\":\"Dra. Ruiz\"}")).andExpect(status().isCreated()).andExpect(header().string("Location","/api/clinical/sessions/5")).andExpect(jsonPath("$.evolution").value("El paciente presenta avances"));}
 @Test void rejectsInvalidSession() throws Exception{mvc.perform(post("/api/clinical/sessions").contentType(MediaType.APPLICATION_JSON).content("{\"processId\":1,\"appointmentId\":10,\"evolution\":\"\",\"registeredBy\":\"\"}")).andExpect(status().isBadRequest());}
 @Test void exposesNoSessionMutationEndpoint() throws Exception{mvc.perform(patch("/api/clinical/sessions/5").contentType(MediaType.APPLICATION_JSON).content("{\"evolution\":\"alterada\"}")).andExpect(status().isMethodNotAllowed());mvc.perform(delete("/api/clinical/sessions/5")).andExpect(status().isMethodNotAllowed());}
}
