package pe.com.cpp.clinical.api;
import static org.mockito.ArgumentMatchers.*; import static org.mockito.Mockito.*; import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*; import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;
import java.time.LocalDateTime; import java.util.*; import org.junit.jupiter.api.Test; import org.springframework.beans.factory.annotation.Autowired; import org.springframework.boot.test.autoconfigure.web.servlet.WebMvcTest; import org.springframework.http.MediaType; import org.springframework.test.context.bean.override.mockito.MockitoBean; import org.springframework.test.web.servlet.MockMvc; import pe.com.cpp.clinical.service.DiagnosisService;
@WebMvcTest(DiagnosisController.class) class DiagnosisControllerTest {
 @Autowired MockMvc mvc; @MockitoBean DiagnosisService service;
 @Test void searchesCie10() throws Exception{when(service.search("ansiedad")).thenReturn(List.of(new Cie10DiagnosisResponse("F41.1","Trastorno de ansiedad generalizada")));mvc.perform(get("/api/clinical/diagnoses/cie10?q=ansiedad")).andExpect(status().isOk()).andExpect(jsonPath("$[0].code").value("F41.1"));}
 @Test void registersHypothesis() throws Exception{when(service.register(eq(7),any())).thenReturn(new HypothesisResponse(3,7,null,2,"Hipótesis","Plan",List.of(new Cie10DiagnosisResponse("F41.1","Ansiedad")),"Dra.",LocalDateTime.now()));mvc.perform(post("/api/clinical/processes/7/hypotheses").contentType(MediaType.APPLICATION_JSON).content("{\"hypothesis\":\"Hipótesis\",\"therapeuticPlan\":\"Plan\",\"diagnosisCodes\":[\"F41.1\"],\"registeredBy\":\"Dra.\"}")).andExpect(status().isCreated()).andExpect(jsonPath("$.diagnoses[0].code").value("F41.1"));}
 @Test void rejectsEmptyDiagnoses() throws Exception{mvc.perform(post("/api/clinical/processes/7/hypotheses").contentType(MediaType.APPLICATION_JSON).content("{\"hypothesis\":\"Hipótesis\",\"therapeuticPlan\":\"Plan\",\"diagnosisCodes\":[],\"registeredBy\":\"Dra.\"}")).andExpect(status().isBadRequest());}
}
