package pe.com.cpp.clinical.api;
import static org.mockito.ArgumentMatchers.*; import static org.mockito.Mockito.*; import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*; import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*; import java.time.*; import org.junit.jupiter.api.Test; import org.springframework.beans.factory.annotation.Autowired; import org.springframework.boot.test.autoconfigure.web.servlet.WebMvcTest; import org.springframework.http.MediaType; import org.springframework.test.context.bean.override.mockito.MockitoBean; import org.springframework.test.web.servlet.MockMvc; import pe.com.cpp.clinical.service.DischargeService;
@WebMvcTest(DischargeController.class) class DischargeControllerTest {
 @Autowired MockMvc mvc; @MockitoBean DischargeService service;
 private DischargeReportResponse report(){return new DischargeReportResponse(3,7,"ALTA","Ana Torres","76543210","HC-0001","Dra. Ruiz",LocalDate.of(2026,1,1),LocalDate.of(2026,7,13),194,12,"Objetivos alcanzados","Resumen","Logros","Recomendaciones","Dra. Ruiz",LocalDateTime.of(2026,7,13,10,0));}
 @Test void registersMedicalDischarge() throws Exception{when(service.discharge(eq(7),any())).thenReturn(report());mvc.perform(post("/api/clinical/processes/7/discharge").contentType(MediaType.APPLICATION_JSON).content("{\"dischargeReason\":\"Objetivos alcanzados\",\"treatmentSummary\":\"Resumen\",\"achievements\":\"Logros\",\"recommendations\":\"Recomendaciones\",\"registeredBy\":\"Dra. Ruiz\"}")).andExpect(status().isCreated()).andExpect(header().string("Location","/api/clinical/processes/7/discharge-report")).andExpect(jsonPath("$.status").value("ALTA"));}
 @Test void rejectsIncompleteDischarge() throws Exception{mvc.perform(post("/api/clinical/processes/7/discharge").contentType(MediaType.APPLICATION_JSON).content("{}" )).andExpect(status().isBadRequest());}
 @Test void obtainsFinalReport() throws Exception{when(service.report(7)).thenReturn(report());mvc.perform(get("/api/clinical/processes/7/discharge-report")).andExpect(status().isOk()).andExpect(jsonPath("$.sessionCount").value(12));}
}
