CREATE TABLE specialty (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    description VARCHAR(300),
    fee NUMERIC(10, 2) NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT uq_specialty_name UNIQUE (name),
    CONSTRAINT chk_specialty_fee CHECK (fee >= 0)
);

CREATE TABLE psychologist (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_names VARCHAR(100) NOT NULL,
    last_names VARCHAR(100) NOT NULL,
    license_number VARCHAR(50) NOT NULL,
    phone VARCHAR(20),
    email VARCHAR(150),
    specialty_id INTEGER NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT uq_psychologist_license UNIQUE (license_number),
    CONSTRAINT fk_psychologist_specialty FOREIGN KEY (specialty_id) REFERENCES specialty (id)
);

CREATE INDEX idx_psychologist_specialty ON psychologist (specialty_id);

CREATE TABLE psychologist_schedule (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    psychologist_id INTEGER NOT NULL,
    day_of_week INTEGER NOT NULL,
    start_time TIME NOT NULL,
    end_time TIME NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT fk_schedule_psychologist FOREIGN KEY (psychologist_id) REFERENCES psychologist (id),
    CONSTRAINT uq_psychologist_schedule UNIQUE (psychologist_id, day_of_week, start_time),
    CONSTRAINT chk_schedule_day CHECK (day_of_week BETWEEN 1 AND 7),
    CONSTRAINT chk_schedule_times CHECK (start_time < end_time)
);

CREATE TABLE appointment (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id INTEGER NOT NULL,
    patient_name VARCHAR(201) NOT NULL,
    patient_dni VARCHAR(8) NOT NULL,
    patient_history_number VARCHAR(20) NOT NULL,
    psychologist_id INTEGER NOT NULL,
    specialty_id INTEGER NOT NULL,
    appointment_date DATE NOT NULL,
    appointment_time TIME NOT NULL,
    status VARCHAR(30) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_appointment_psychologist FOREIGN KEY (psychologist_id) REFERENCES psychologist (id),
    CONSTRAINT fk_appointment_specialty FOREIGN KEY (specialty_id) REFERENCES specialty (id),
    CONSTRAINT chk_appointment_status CHECK (status IN (
        'PENDING_PAYMENT', 'PAID', 'ON_FLOOR', 'IN_CONSULTATION', 'ATTENDED', 'CANCELLED'
    ))
);

CREATE INDEX idx_appointment_patient ON appointment (patient_id, created_at DESC);
CREATE INDEX idx_appointment_date ON appointment (appointment_date, appointment_time);
CREATE UNIQUE INDEX uq_active_appointment_slot
    ON appointment (psychologist_id, appointment_date, appointment_time)
    WHERE status NOT IN ('CANCELLED', 'ATTENDED');

INSERT INTO specialty (name, description, fee) VALUES
    ('Psicologia Clinica', 'Evaluacion y tratamiento de trastornos psicologicos', 80.00),
    ('Psicologia Infantil', 'Atencion especializada en ninos y adolescentes', 80.00),
    ('Psicologia Organizacional', 'Intervencion en entornos laborales y organizacionales', 90.00),
    ('Neuropsicologia', 'Evaluacion de funciones cognitivas y conductuales', 100.00),
    ('Terapia de Pareja', 'Intervencion en dinamicas relacionales y familiares', 90.00);

INSERT INTO psychologist
    (first_names, last_names, license_number, phone, email, specialty_id)
SELECT 'Jose', 'Martinez Vargas', 'CPP-12345', '987654321',
       'jose.martinez@clinica.local', id
FROM specialty WHERE name = 'Psicologia Clinica';

INSERT INTO psychologist_schedule (psychologist_id, day_of_week, start_time, end_time)
SELECT p.id, day_number, TIME '08:00', TIME '19:00'
FROM psychologist p
CROSS JOIN generate_series(1, 6) AS day_number
WHERE p.license_number = 'CPP-12345';
