-- ============================================================
-- SISTEMA CLINICAS PSICOLOGIA DEL PERU
-- Base de datos: PostgreSQL / Neon
-- ============================================================

-- Ejecutar conectado a la base configurada en DB_NAME.
-- En Neon normalmente no se crea la base desde este script.

-- ============================================================
-- TABLAS
-- ============================================================

CREATE TABLE IF NOT EXISTS rol (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre      VARCHAR(50) NOT NULL UNIQUE,
    descripcion VARCHAR(200)
);

CREATE TABLE IF NOT EXISTS usuario (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username        VARCHAR(50) NOT NULL UNIQUE,
    password_hash   VARCHAR(255) NOT NULL,
    nombre_completo VARCHAR(150) NOT NULL,
    rol_id          INTEGER NOT NULL REFERENCES rol(id),
    activo          BOOLEAN NOT NULL DEFAULT TRUE,
    creado_en       TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    email           VARCHAR(150) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS especialidad (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre      VARCHAR(100) NOT NULL UNIQUE,
    descripcion VARCHAR(300),
    tarifa      NUMERIC(10,2) NOT NULL DEFAULT 80.00,
    activo      BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS psicologo (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id      INTEGER REFERENCES usuario(id),
    nombres         VARCHAR(100) NOT NULL,
    apellidos       VARCHAR(100) NOT NULL,
    colegiatura     VARCHAR(50) NOT NULL UNIQUE,
    telefono        VARCHAR(20),
    email           VARCHAR(150),
    especialidad_id INTEGER NOT NULL REFERENCES especialidad(id),
    activo          BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS horariopsicologo (
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    psicologo_id  INTEGER NOT NULL REFERENCES psicologo(id),
    dia_semana    INTEGER NOT NULL CHECK (dia_semana BETWEEN 1 AND 6),
    hora_inicio   TIME NOT NULL,
    hora_fin      TIME NOT NULL,
    activo        BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT uq_horario UNIQUE (psicologo_id, dia_semana, hora_inicio)
);

CREATE TABLE IF NOT EXISTS paciente (
    id               INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    numero_historia  VARCHAR(20) NOT NULL UNIQUE,
    dni              VARCHAR(8) NOT NULL UNIQUE,
    nombres          VARCHAR(100) NOT NULL,
    apellidos        VARCHAR(100) NOT NULL,
    fecha_nacimiento DATE NOT NULL,
    sexo             CHAR(1) NOT NULL CHECK (sexo IN ('M', 'F')),
    telefono         VARCHAR(20),
    email            VARCHAR(150),
    direccion        VARCHAR(250),
    creado_en        TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    activo           BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS ticket (
    id        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    numero    VARCHAR(10) NOT NULL,
    fecha     DATE NOT NULL DEFAULT CURRENT_DATE,
    estado    VARCHAR(20) NOT NULL DEFAULT 'ESPERA'
              CHECK (estado IN ('ESPERA', 'EN_ATENCION', 'FINALIZADO')),
    creado_en TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_ticket_fecha_numero UNIQUE (fecha, numero)
);

CREATE TABLE IF NOT EXISTS cita (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    paciente_id     INTEGER NOT NULL REFERENCES paciente(id),
    psicologo_id    INTEGER NOT NULL REFERENCES psicologo(id),
    especialidad_id INTEGER NOT NULL REFERENCES especialidad(id),
    ticket_id       INTEGER REFERENCES ticket(id),
    fecha_cita      DATE NOT NULL,
    hora_cita       TIME NOT NULL,
    estado          VARCHAR(20) NOT NULL DEFAULT 'PENDIENTE_PAGO'
                    CHECK (estado IN ('PENDIENTE_PAGO', 'PAGADA', 'EN_CONSULTA', 'ATENDIDA', 'CANCELADA')),
    creado_por      INTEGER REFERENCES usuario(id),
    creado_en       TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_cita_psicologo_fecha_hora UNIQUE (psicologo_id, fecha_cita, hora_cita)
);

CREATE TABLE IF NOT EXISTS deuda (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    paciente_id INTEGER NOT NULL REFERENCES paciente(id),
    cita_id     INTEGER REFERENCES cita(id),
    concepto    VARCHAR(100) NOT NULL,
    monto       NUMERIC(10,2) NOT NULL,
    estado      VARCHAR(20) NOT NULL DEFAULT 'PENDIENTE'
                CHECK (estado IN ('PENDIENTE', 'PAGADA')),
    creado_en   TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS comprobantepago (
    id                 INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    numero_serie       VARCHAR(20) NOT NULL UNIQUE,
    tipo               VARCHAR(20) NOT NULL DEFAULT 'BOLETA'
                       CHECK (tipo IN ('BOLETA', 'FACTURA')),
    deuda_id           INTEGER NOT NULL REFERENCES deuda(id),
    medio_pago         VARCHAR(30) NOT NULL
                       CHECK (medio_pago IN ('EFECTIVO', 'TARJETA', 'YAPE_PLIN')),
    monto_pagado       NUMERIC(10,2) NOT NULL,
    fecha_emision      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS procesoterapeutico (
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    paciente_id   INTEGER NOT NULL REFERENCES paciente(id),
    psicologo_id  INTEGER NOT NULL REFERENCES psicologo(id),
    fase_actual   INTEGER NOT NULL DEFAULT 1 CHECK (fase_actual BETWEEN 1 AND 4),
    fecha_inicio  DATE NOT NULL DEFAULT CURRENT_DATE,
    fecha_fin     DATE,
    observaciones TEXT,
    activo        BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_proceso_activo
    ON procesoterapeutico (paciente_id, psicologo_id)
    WHERE activo = TRUE;

CREATE TABLE IF NOT EXISTS sesion (
    id                     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cita_id                INTEGER NOT NULL REFERENCES cita(id),
    proceso_terapeutico_id INTEGER NOT NULL REFERENCES procesoterapeutico(id),
    fase_sesion            INTEGER NOT NULL CHECK (fase_sesion BETWEEN 1 AND 4),
    evolucion              TEXT NOT NULL,
    indicaciones_paciente  TEXT,
    fecha_registro         TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    registrado_por         INTEGER REFERENCES usuario(id)
);

-- ============================================================
-- DATOS INICIALES
-- ============================================================

INSERT INTO rol (nombre, descripcion) VALUES
    ('ADMIN', 'Administrador del sistema'),
    ('RECEPCION', 'Personal de recepcion'),
    ('CAJA', 'Cajero de consultorios'),
    ('PSICOLOGO', 'Psicologo tratante'),
    ('ANFITRIONA', 'Personal de bienvenida y tickets')
ON CONFLICT (nombre) DO NOTHING;

INSERT INTO especialidad (nombre, descripcion, tarifa) VALUES
    ('Psicologia Clinica', 'Evaluacion y tratamiento de trastornos psicologicos', 80.00),
    ('Psicologia Infantil', 'Atencion especializada en ninos y adolescentes', 80.00),
    ('Psicologia Organizacional', 'Intervencion en entornos laborales y organizacionales', 90.00),
    ('Neuropsicologia', 'Evaluacion de funciones cognitivas y conductuales', 100.00),
    ('Terapia de Pareja', 'Intervencion en dinamicas relacionales y familiares', 90.00)
ON CONFLICT (nombre) DO NOTHING;

-- Password demo: 123
DO $$
DECLARE
    hash_pass TEXT := '$2a$10$2OrRLP6u9I0Txwl8gNJmPeQOI4BSAPZt865HXfsSwm1tuVQmshkWm';
BEGIN
    INSERT INTO usuario (username, password_hash, nombre_completo, rol_id, email)
    SELECT 'admin', hash_pass, 'Administrador del Sistema', r.id, 'admin@clinica.local'
    FROM rol r WHERE r.nombre = 'ADMIN'
    ON CONFLICT (username) DO NOTHING;

    INSERT INTO usuario (username, password_hash, nombre_completo, rol_id, email)
    SELECT 'recepcion', hash_pass, 'Maria Recepcionista Lopez', r.id, 'recepcion@clinica.local'
    FROM rol r WHERE r.nombre = 'RECEPCION'
    ON CONFLICT (username) DO NOTHING;

    INSERT INTO usuario (username, password_hash, nombre_completo, rol_id, email)
    SELECT 'caja', hash_pass, 'Carlos Cajero Quispe', r.id, 'caja@clinica.local'
    FROM rol r WHERE r.nombre = 'CAJA'
    ON CONFLICT (username) DO NOTHING;

    INSERT INTO usuario (username, password_hash, nombre_completo, rol_id, email)
    SELECT 'psicologo', hash_pass, 'Dr. Jose Martinez Vargas', r.id, 'psicologo@clinica.local'
    FROM rol r WHERE r.nombre = 'PSICOLOGO'
    ON CONFLICT (username) DO NOTHING;

    INSERT INTO usuario (username, password_hash, nombre_completo, rol_id, email)
    SELECT 'anfitriona', hash_pass, 'Ana Anfitriona Ramos', r.id, 'anfitriona@clinica.local'
    FROM rol r WHERE r.nombre = 'ANFITRIONA'
    ON CONFLICT (username) DO NOTHING;
END $$;

DO $$
DECLARE
    esp_id INTEGER;
    usr_psic INTEGER;
    psic_id INTEGER;
BEGIN
    SELECT id INTO esp_id
    FROM especialidad
    WHERE nombre = 'Psicologia Clinica';

    SELECT id INTO usr_psic
    FROM usuario
    WHERE username = 'psicologo';

    INSERT INTO psicologo (usuario_id, nombres, apellidos, colegiatura, telefono, email, especialidad_id)
    VALUES (usr_psic, 'Jose', 'Martinez Vargas', 'CPP-12345', '987654321', 'jose.martinez@clinica.local', esp_id)
    ON CONFLICT (colegiatura) DO UPDATE
    SET usuario_id = EXCLUDED.usuario_id
    RETURNING id INTO psic_id;

    IF psic_id IS NULL THEN
        SELECT id INTO psic_id FROM psicologo WHERE colegiatura = 'CPP-12345';
    END IF;

    INSERT INTO horariopsicologo (psicologo_id, dia_semana, hora_inicio, hora_fin) VALUES
        (psic_id, 1, '08:00', '19:00'),
        (psic_id, 2, '08:00', '19:00'),
        (psic_id, 3, '08:00', '19:00'),
        (psic_id, 4, '08:00', '19:00'),
        (psic_id, 5, '08:00', '19:00'),
        (psic_id, 6, '08:00', '19:00')
    ON CONFLICT (psicologo_id, dia_semana, hora_inicio) DO NOTHING;
END $$;

INSERT INTO paciente (numero_historia, dni, nombres, apellidos, fecha_nacimiento, sexo, telefono, email) VALUES
    ('HC-0001', '76543210', 'Maria', 'Gonzalez Perez', '1990-05-15', 'F', '999888777', 'maria.gonzalez@email.local'),
    ('HC-0002', '12345678', 'Juan', 'Perez Torres', '1985-03-22', 'M', '911222333', 'juan.perez@email.local')
ON CONFLICT (dni) DO NOTHING;
