-- ============================================================
-- PATCH NEON: Entrevista inicial (Fase 1 del proceso terapeutico, HU17)
-- Ejecutar una sola vez sobre la base existente.
-- ============================================================

CREATE TABLE IF NOT EXISTS entrevistainicial (
    id                      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    proceso_terapeutico_id  INTEGER NOT NULL UNIQUE REFERENCES procesoterapeutico(id),
    motivo_consulta         TEXT NOT NULL,
    antecedentes_personales TEXT,
    antecedentes_familiares TEXT,
    observaciones_iniciales TEXT,
    fecha_registro          TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
