package pe.com.cpp.clinical.service;
import java.time.*; import java.time.temporal.ChronoUnit; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import pe.com.cpp.clinical.api.*; import pe.com.cpp.clinical.client.*; import pe.com.cpp.clinical.domain.*; import pe.com.cpp.clinical.exception.*; import pe.com.cpp.clinical.repository.*;
@Service public class DischargeService {
 private final TherapeuticProcessRepository processes; private final ClinicalDischargeReportRepository reports; private final ClinicalSessionRepository sessions; private final QueueClient queue; private final Clock clock;
 @org.springframework.beans.factory.annotation.Autowired public DischargeService(TherapeuticProcessRepository processes,ClinicalDischargeReportRepository reports,ClinicalSessionRepository sessions,QueueClient queue){this(processes,reports,sessions,queue,Clock.systemDefaultZone());}
 DischargeService(TherapeuticProcessRepository processes,ClinicalDischargeReportRepository reports,ClinicalSessionRepository sessions,QueueClient queue,Clock clock){this.processes=processes;this.reports=reports;this.sessions=sessions;this.queue=queue;this.clock=clock;}
 @Transactional public DischargeReportResponse discharge(Integer processId,DischargeRequest request){TherapeuticProcess process=findProcess(processId);if(!process.isActive()||reports.existsByProcessId(processId))throw new DuplicateClinicalRecordException("El proceso ya tiene alta médica");if(process.getCurrentPhase()!=4)throw new BusinessRuleException("El alta médica solo puede registrarse en Fase 4");if(process.getInitialAppointmentId()==null)throw new BusinessRuleException("El proceso no tiene una cita inicial vinculada para calcular productividad");QueueTicketSnapshot ticket=queue.findByAppointment(process.getInitialAppointmentId());if(ticket.patientId()!=null&&!process.getPatientId().equals(ticket.patientId()))throw new BusinessRuleException("El ticket no corresponde al paciente del proceso");LocalDateTime now=LocalDateTime.now(clock);if(ticket.createdAt()==null||ticket.createdAt().isAfter(now))throw new BusinessRuleException("La fecha de emisión del ticket no es válida");ClinicalDischargeReport report=reports.save(new ClinicalDischargeReport(process,request.dischargeReason().trim(),request.treatmentSummary().trim(),request.achievements().trim(),request.recommendations().trim(),request.registeredBy().trim(),now,ticket.number(),ticket.createdAt()));process.discharge(now.toLocalDate());processes.save(process);return toResponse(report);}
 @Transactional(readOnly=true) public DischargeReportResponse report(Integer processId){findProcess(processId);return toResponse(reports.findByProcessId(processId).orElseThrow(()->new ResourceNotFoundException("Informe de alta no encontrado")));}
 @Transactional(readOnly=true) public DischargeReportResponse latestReportForPatient(Integer patientId){TherapeuticProcess process=processes.findFirstByPatientIdOrderByStartDateDescIdDesc(patientId).orElseThrow(()->new ResourceNotFoundException("El paciente no tiene historia clínica"));return report(process.getId());}
 private TherapeuticProcess findProcess(Integer id){return processes.findById(id).orElseThrow(()->new ResourceNotFoundException("Proceso terapéutico no encontrado"));}
 private DischargeReportResponse toResponse(ClinicalDischargeReport report){TherapeuticProcess p=report.getProcess();LocalDate end=p.getEndDate()==null?report.getDischargedAt().toLocalDate():p.getEndDate();long days=ChronoUnit.DAYS.between(p.getStartDate(),end)+1;return new DischargeReportResponse(report.getId(),p.getId(),"ALTA",p.getPatientName(),p.getPatientDni(),p.getPatientHistoryNumber(),p.getPsychologistName(),p.getStartDate(),end,days,sessions.countByProcessId(p.getId()),report.getDischargeReason(),report.getTreatmentSummary(),report.getAchievements(),report.getRecommendations(),report.getRegisteredBy(),report.getDischargedAt());}
}
