package pe.com.cpp.clinical.service;
import java.time.*; import java.util.*; import java.util.stream.*; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import pe.com.cpp.clinical.api.*; import pe.com.cpp.clinical.exception.BusinessRuleException; import pe.com.cpp.clinical.repository.*;
@Service public class ProductivityService {
 private final ClinicalDischargeReportRepository reports; private final Clock clock;
 @org.springframework.beans.factory.annotation.Autowired public ProductivityService(ClinicalDischargeReportRepository reports){this(reports,Clock.systemDefaultZone());} ProductivityService(ClinicalDischargeReportRepository reports,Clock clock){this.reports=reports;this.clock=clock;}
 @Transactional(readOnly=true) public ProductivityReportResponse report(LocalDate from,LocalDate to){LocalDate end=to==null?LocalDate.now(clock):to;LocalDate start=from==null?end.minusDays(29):from;if(start.isAfter(end))throw new BusinessRuleException("La fecha inicial no puede ser posterior a la fecha final");if(start.isBefore(end.minusYears(2)))throw new BusinessRuleException("El periodo máximo del reporte es de dos años");List<ProductivityCaseResponse> cases=reports.findProductivityCases(start,end).stream().map(this::toCase).toList();DoubleSummaryStatistics stats=cases.stream().mapToDouble(ProductivityCaseResponse::efficiencyHours).summaryStatistics();Map<LocalDate,List<ProductivityCaseResponse>> daily=cases.stream().collect(Collectors.groupingBy(c->c.dischargedAt().toLocalDate(),TreeMap::new,Collectors.toList()));Map<String,List<ProductivityCaseResponse>> psychologists=cases.stream().collect(Collectors.groupingBy(ProductivityCaseResponse::psychologistName,TreeMap::new,Collectors.toList()));List<ProductivityTrendResponse> trend=daily.entrySet().stream().map(e->new ProductivityTrendResponse(e.getKey(),e.getValue().size(),average(e.getValue()))).toList();List<PsychologistProductivityResponse> byPsychologist=psychologists.entrySet().stream().map(e->new PsychologistProductivityResponse(e.getKey(),e.getValue().size(),average(e.getValue()))).toList();return new ProductivityReportResponse(start,end,stats.getCount(),round(stats.getCount()==0?0:stats.getAverage()),round(stats.getCount()==0?0:stats.getMin()),round(stats.getCount()==0?0:stats.getMax()),trend,byPsychologist,cases);}
 private ProductivityCaseResponse toCase(ProductivityCaseProjection p){return new ProductivityCaseResponse(p.getReportId(),p.getTicketNumber(),p.getPatientName(),p.getPatientHistoryNumber(),p.getPsychologistName(),p.getTicketIssuedAt(),p.getDischargedAt(),p.getEfficiencyHours());}
 private double average(List<ProductivityCaseResponse> cases){return round(cases.stream().mapToDouble(ProductivityCaseResponse::efficiencyHours).average().orElse(0));} private double round(double value){return Math.round(value*100.0)/100.0;}
}
