ALTER TABLE therapeutic_process
    ADD COLUMN status VARCHAR(20) NOT NULL DEFAULT 'ACTIVO',
    ADD CONSTRAINT chk_process_status CHECK (status IN ('ACTIVO', 'ALTA'));

CREATE TABLE clinical_discharge_report (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    therapeutic_process_id INTEGER NOT NULL,
    discharge_reason TEXT NOT NULL,
    treatment_summary TEXT NOT NULL,
    achievements TEXT NOT NULL,
    recommendations TEXT NOT NULL,
    registered_by VARCHAR(201) NOT NULL,
    discharged_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_discharge_process FOREIGN KEY (therapeutic_process_id) REFERENCES therapeutic_process (id),
    CONSTRAINT uq_discharge_process UNIQUE (therapeutic_process_id),
    CONSTRAINT chk_discharge_reason CHECK (length(trim(discharge_reason)) > 0),
    CONSTRAINT chk_discharge_summary CHECK (length(trim(treatment_summary)) > 0)
);

CREATE FUNCTION reject_discharged_process_mutation() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'DELETE' OR OLD.status = 'ALTA' THEN
        RAISE EXCEPTION 'La historia clinica con alta no puede modificarse ni eliminarse';
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_discharged_process_locked
BEFORE UPDATE OR DELETE ON therapeutic_process
FOR EACH ROW EXECUTE FUNCTION reject_discharged_process_mutation();

CREATE FUNCTION require_active_therapeutic_process() RETURNS trigger AS $$
DECLARE process_active BOOLEAN;
BEGIN
    SELECT active INTO process_active FROM therapeutic_process WHERE id = NEW.therapeutic_process_id;
    IF process_active IS DISTINCT FROM TRUE THEN
        RAISE EXCEPTION 'La historia clinica esta cerrada por alta';
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_session_requires_active_process
BEFORE INSERT ON clinical_session
FOR EACH ROW EXECUTE FUNCTION require_active_therapeutic_process();

CREATE TRIGGER trg_hypothesis_requires_active_process
BEFORE INSERT ON clinical_hypothesis
FOR EACH ROW EXECUTE FUNCTION require_active_therapeutic_process();

CREATE FUNCTION reject_discharge_report_mutation() RETURNS trigger AS $$
BEGIN
    RAISE EXCEPTION 'El informe de alta es inmutable';
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_discharge_report_immutable
BEFORE UPDATE OR DELETE ON clinical_discharge_report
FOR EACH ROW EXECUTE FUNCTION reject_discharge_report_mutation();
