package pe.com.cpp.queue.service;
import static org.junit.jupiter.api.Assertions.*; import static org.mockito.Mockito.*;
import java.time.*; import java.util.*; import org.junit.jupiter.api.*; import org.mockito.*; import org.springframework.test.util.ReflectionTestUtils; import pe.com.cpp.queue.api.*; import pe.com.cpp.queue.domain.*; import pe.com.cpp.queue.exception.*; import pe.com.cpp.queue.repository.*;
class QueueServiceTest {
 @Mock QueueTicketRepository tickets; @Mock DailyTicketSequenceRepository sequences; Clock clock; QueueService service; DailyTicketSequence sequence;
 @BeforeEach void setUp(){MockitoAnnotations.openMocks(this);clock=Clock.fixed(Instant.parse("2026-07-13T04:30:00Z"),ZoneId.of("America/Lima"));service=new QueueService(tickets,sequences,clock);sequence=new DailyTicketSequence(LocalDate.of(2026,7,12));when(sequences.findByDateForUpdate(any())).thenReturn(Optional.of(sequence));when(tickets.saveAndFlush(any())).thenAnswer(i->i.getArgument(0));when(tickets.save(any())).thenAnswer(i->i.getArgument(0));}
 private QueueTicket ticket(long id,String number){QueueTicket t=new QueueTicket(number,LocalDate.of(2026,7,12),LocalDateTime.of(2026,7,12,23,30));ReflectionTestUtils.setField(t,"id",id);return t;}
 @Test void firstTicketOfDay(){assertEquals("A-001",service.issue().number());}
 @Test void incrementsCorrelatively(){service.issue();assertEquals("A-002",service.issue().number());}
 @Test void usesLimaOperationalDate(){assertEquals(LocalDate.of(2026,7,12),service.issue().operationalDate());}
 @Test void resetsOnNewDate(){Clock next=Clock.fixed(Instant.parse("2026-07-13T15:00:00Z"),ZoneId.of("America/Lima"));DailyTicketSequence nextSequence=new DailyTicketSequence(LocalDate.of(2026,7,13));when(sequences.findByDateForUpdate(LocalDate.of(2026,7,13))).thenReturn(Optional.of(nextSequence));QueueService nextService=new QueueService(tickets,sequences,next);assertEquals("A-001",nextService.issue().number());}
 @Test void validTransitions(){QueueTicket t=ticket(1,"A-001");when(tickets.findByIdForUpdate(1L)).thenReturn(Optional.of(t));assertEquals(TicketStatus.EN_ATENCION,service.call(1L).status());assertEquals(TicketStatus.FINALIZADO,service.finish(1L).status());}
 @Test void rejectsInvalidFinish(){QueueTicket t=ticket(1,"A-001");when(tickets.findByIdForUpdate(1L)).thenReturn(Optional.of(t));assertThrows(QueueConflictException.class,()->service.finish(1L));}
 @Test void missingTicket(){when(tickets.findByIdForUpdate(99L)).thenReturn(Optional.empty());assertThrows(ResourceNotFoundException.class,()->service.call(99L));}
 @Test void onlyOneActiveTicket(){QueueTicket first=ticket(1,"A-001"),second=ticket(2,"A-002");when(tickets.findByIdForUpdate(1L)).thenReturn(Optional.of(first));when(tickets.findByIdForUpdate(2L)).thenReturn(Optional.of(second));service.call(1L);assertThrows(QueueConflictException.class,()->service.call(2L));}
 @Test void displayLimitsWaitingList(){List<QueueTicket> waiting=List.of(ticket(1,"A-001"),ticket(2,"A-002"),ticket(3,"A-003"),ticket(4,"A-004"));when(tickets.findByOperationalDateAndStatusOrderByCreatedAtAsc(any(),eq(TicketStatus.ESPERA))).thenReturn(waiting);assertEquals(3,service.display().next().size());}
 @Test void issuesAndFindsAppointmentTicket(){TicketResponse issued=service.issueForAppointment(10,1);assertEquals(10,issued.appointmentId());QueueTicket linked=new QueueTicket("A-001",LocalDate.of(2026,7,12),LocalDateTime.now(),10,1);when(tickets.findByAppointmentId(10)).thenReturn(Optional.of(linked));assertEquals(1,service.byAppointment(10).patientId());}
 @Test void repeatedAppointmentTicketIsIdempotent(){QueueTicket linked=new QueueTicket("A-001",LocalDate.of(2026,7,12),LocalDateTime.now(),10,1);when(tickets.findByAppointmentId(10)).thenReturn(Optional.of(linked));assertEquals("A-001",service.issueForAppointment(10,1).number());verify(tickets,never()).saveAndFlush(any());}
 @Test void rejectsAppointmentTicketForAnotherPatient(){QueueTicket linked=new QueueTicket("A-001",LocalDate.of(2026,7,12),LocalDateTime.now(),10,2);when(tickets.findByAppointmentId(10)).thenReturn(Optional.of(linked));assertThrows(QueueConflictException.class,()->service.issueForAppointment(10,1));}
 @Test void attachesExistingTicketToAppointment(){QueueTicket existing=ticket(1,"A-001");when(tickets.findByIdForUpdate(1L)).thenReturn(Optional.of(existing));when(tickets.findByAppointmentId(10)).thenReturn(Optional.empty());TicketResponse attached=service.attach(1L,10,1);assertEquals(10,attached.appointmentId());assertEquals(1,attached.patientId());}
 @Test void rejectsAttachingAppointmentAlreadyLinkedToAnotherTicket(){QueueTicket existing=ticket(1,"A-001"),linked=ticket(2,"A-002");when(tickets.findByIdForUpdate(1L)).thenReturn(Optional.of(existing));when(tickets.findByAppointmentId(10)).thenReturn(Optional.of(linked));assertThrows(QueueConflictException.class,()->service.attach(1L,10,1));}
}
